# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='log.proto',
  package='service.logging',
  syntax='proto3',
  serialized_pb=_b('\n\tlog.proto\x12\x0fservice.logging\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x02\n\x03Log\x12-\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x1c.service.logging.Log.Context\x12)\n\x05level\x18\x02 \x01(\x0e\x32\x1a.service.logging.Log.Level\x12\x0f\n\x07message\x18\x03 \x01(\t\x1ap\n\x07\x43ontext\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nhost_or_ip\x18\x02 \x01(\t\x12\x14\n\x0cservice_name\x18\x03 \x01(\t\x12\x0c\n\x04user\x18\x04 \x01(\t\"<\n\x05Level\x12\t\n\x05\x44\x45\x42UG\x10\x00\x12\x08\n\x04INFO\x10\x01\x12\x08\n\x04WARN\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x12\t\n\x05\x46\x41TAL\x10\x04\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_LOG_LEVEL = _descriptor.EnumDescriptor(
  name='Level',
  full_name='service.logging.Log.Level',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEBUG', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INFO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FATAL', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=292,
  serialized_end=352,
)
_sym_db.RegisterEnumDescriptor(_LOG_LEVEL)


_LOG_CONTEXT = _descriptor.Descriptor(
  name='Context',
  full_name='service.logging.Log.Context',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='service.logging.Log.Context.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host_or_ip', full_name='service.logging.Log.Context.host_or_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service_name', full_name='service.logging.Log.Context.service_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='service.logging.Log.Context.user', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=290,
)

_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='service.logging.Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='service.logging.Log.context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='service.logging.Log.level', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='service.logging.Log.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LOG_CONTEXT, ],
  enum_types=[
    _LOG_LEVEL,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=352,
)

_LOG_CONTEXT.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_LOG_CONTEXT.containing_type = _LOG
_LOG.fields_by_name['context'].message_type = _LOG_CONTEXT
_LOG.fields_by_name['level'].enum_type = _LOG_LEVEL
_LOG_LEVEL.containing_type = _LOG
DESCRIPTOR.message_types_by_name['Log'] = _LOG

Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), dict(

  Context = _reflection.GeneratedProtocolMessageType('Context', (_message.Message,), dict(
    DESCRIPTOR = _LOG_CONTEXT,
    __module__ = 'log_pb2'
    # @@protoc_insertion_point(class_scope:service.logging.Log.Context)
    ))
  ,
  DESCRIPTOR = _LOG,
  __module__ = 'log_pb2'
  # @@protoc_insertion_point(class_scope:service.logging.Log)
  ))
_sym_db.RegisterMessage(Log)
_sym_db.RegisterMessage(Log.Context)


# @@protoc_insertion_point(module_scope)
